kadi/modules/main/forms.py
# Copyright 2022 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask_babel import lazy_gettext as _l

from kadi.lib.forms import BaseForm
from kadi.lib.forms import SubmitField


class AuthorizeApplicationForm(BaseForm):
    """A form for use in authorizing an OAuth2 application."""

    submit_auth = SubmitField(_l("Authorize"))

    submit_deny = SubmitField(_l("Deny"))

kadi/modules/main/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kadi/modules/main/api/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import internal
from . import public

kadi/modules/main/api/internal/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import delete
from . import get
from . import patch
from . import post

kadi/modules/main/blueprint.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import Blueprint


bp = Blueprint("main", __name__, template_folder="templates")


from . import views  # pylint: disable=unused-import

kadi/modules/main/views.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from authlib.oauth2 import OAuth2Error
from flask import redirect
from flask import render_template
from flask_babel import gettext as _
from flask_login import current_user
from flask_login import login_required

import kadi.lib.constants as const
from kadi.ext.csrf import csrf
from kadi.ext.oauth import oauth_server
from kadi.lib.config.core import get_sys_config
from kadi.lib.oauth.core import RevocationEndpoint
from kadi.lib.web import get_preferred_locale
from kadi.lib.web import html_error_response
from kadi.lib.web import url_for

from .blueprint import bp
from .forms import AuthorizeApplicationForm
from .utils import get_favorite_resources
from .utils import get_latest_resources
from .utils import get_resource_searches


@bp.get("/")
def index():
    """The index/home page.

    Will change depending on whether the current user is authenticated or not.
    """
    preferred_locale = get_preferred_locale()

    if not current_user.is_authenticated:
        return render_template("main/index.html", preferred_locale=preferred_locale)

    return render_template(
        "main/home.html",
        title=_("Home"),
        preferred_locale=preferred_locale,
        js_context={
            "favorite_resources": get_favorite_resources(),
            "saved_searches": get_resource_searches(),
            "latest_resources": get_latest_resources(),
        },
    )


@bp.get("/about")
def about():
    """The about page."""
    return render_template("main/about.html", title=_("About"))


@bp.get("/help")
def help():
    """The help page."""
    return render_template("main/help.html", title=_("Help"))


@bp.get("/terms-of-use")
def terms_of_use():
    """Page showing the terms of use, if configured."""
    config_item = const.SYS_CONFIG_TERMS_OF_USE

    if not get_sys_config(config_item):
        return redirect(url_for("main.index"))

    return render_template(
        "main/legals.html",
        title=_("Terms of use"),
        endpoint="terms_of_use",
        config_item=config_item,
    )


@bp.get("/privacy-policy")
def privacy_policy():
    """Page showing the privacy policy, if configured."""
    config_item = const.SYS_CONFIG_PRIVACY_POLICY

    if not get_sys_config(config_item):
        return redirect(url_for("main.index"))

    return render_template(
        "main/legals.html",
        title=_("Privacy policy"),
        endpoint="privacy_policy",
        config_item=config_item,
    )


@bp.get("/legal-notice")
def legal_notice():
    """Page showing the legal notice, if configured."""
    config_item = const.SYS_CONFIG_LEGAL_NOTICE

    if not get_sys_config(config_item):
        return redirect(url_for("main.index"))

    return render_template(
        "main/legals.html",
        title=_("Legal notice"),
        endpoint="legal_notice",
        config_item=config_item,
    )


@bp.route("/oauth/authorize", methods=["GET", "POST"])
@login_required
def oauth2_server_authorize():
    """Authorization endpoint for the OAuth2 server implementation."""
    form = AuthorizeApplicationForm()

    if form.validate_on_submit():
        # Check if authorization was granted by the user.
        if form.submit_auth.data:
            grant_user = current_user
        else:
            grant_user = None

        return oauth_server.create_authorization_response(grant_user=grant_user)

    try:
        grant = oauth_server.get_consent_grant(end_user=current_user)
    except OAuth2Error as e:
        description = e.description

        if not description:
            description = _(
                "The service that redirected you here made an invalid authorization"
                " request."
            )

        return html_error_response(e.status_code, description=description)

    return render_template(
        "main/oauth_consent.html",
        title=_("Authorize application"),
        form=form,
        client=grant.client,
    )


@bp.post("/oauth/token")
@csrf.exempt
def oauth2_server_token():
    """Token endpoint for the OAuth2 server implementation."""
    return oauth_server.create_token_response()


@bp.post("/oauth/revoke")
@csrf.exempt
def oauth2_server_revoke():
    """Token revocation endpoint for the OAuth2 server implementation."""
    return oauth_server.create_endpoint_response(RevocationEndpoint.ENDPOINT_NAME)

kadi/modules/main/templates/main/about.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block breadcrumbs %}
  {% include "snippets/breadcrumb_home.html" %}
  {% snippet "snippets/breadcrumb.html", url=url_for("main.about"), title=title %}
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <p>
        {% trans strong_open="<strong>" | safe, strong_close="</strong>" | safe %}
          {{ strong_open }}Kadi4Mat{{ strong_close }}, or {{ strong_open }}Kadi{{ strong_close }} for short, is a
          generic and open source virtual research environment. Originally developed in the context of materials
          science, Kadi4Mat can be used for the management of any type of research data within different research
          disciplines and use cases. Kadi4Mat is being developed as part of several research projects at the {{
          strong_open }}Karlsruhe Institute of Technology (KIT){{ strong_close }}.
        {% endtrans %}
      </p>
      <p>
        {% trans em_open="<em>" | safe, em_close="</em>" | safe %}
          The goal of Kadi4Mat is to combine the ability to manage and exchange data, the {{ em_open }}repository{{
          em_close }} component, with the possibility to analyze, visualize and transform said data, the {{ em_open
          }}electronic lab notebook (ELN){{ em_close }} component. The focus on the repository component is on {{
          em_open }}warm data{{ em_close }}, i.e. unpublished data that is yet to be analyzed further, while in the ELN
          component it is on the automated and documented execution of heterogeneous workflows via an application
          programming interface (API). In this way, a customizable framework is created that facilitates good research
          data management practices and collaboration between researchers.
        {% endtrans %}
      </p>
      <hr>
      <div class="row">
        <div class="col-md-8 mb-4 mb-md-0">
          <ul class="mb-0 pl-3">
            <li>
              {% trans %}More information{% endtrans %}:
              <a href="{{ const.URL_INDEX }}" target="_blank" rel="noopener noreferrer">
                <strong>{{ const.URL_INDEX }}</strong>
              </a>
            </li>
            <li>
              {% trans %}Source code and issue tracking{% endtrans %}:
              <a href="https://gitlab.com/iam-cms/kadi" target="_blank" rel="noopener noreferrer">
                <strong>https://gitlab.com/iam-cms/kadi</strong>
              </a>
            </li>
            <li>
              {% trans %}Documentation{% endtrans %}:
              <ul class="mb-0 pl-4">
                <li>
                  {% trans %}Latest release{% endtrans %}:
                  <a href="{{ const.URL_RTD_STABLE }}" target="_blank" rel="noopener noreferrer">
                    <strong>{{ const.URL_RTD_STABLE }}</strong>
                  </a>
                </li>
                <li>
                  {% trans %}Current state{% endtrans %}:
                  <a href="{{ const.URL_RTD_LATEST }}" target="_blank" rel="noopener noreferrer">
                    <strong>{{ const.URL_RTD_LATEST }}</strong>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="col-md-4 d-md-flex justify-content-end align-items-end">
          <a href="https://www.kit.edu" target="_blank" rel="noopener noreferrer">
            <img class="img-fluid" src="{{ static_url('images/kit.png') }}" width="150">
          </a>
        </div>
      </div>
    </div>
    {% if user_active %}
      <div class="card-footer">
        <a href="{{ const.URL_RTD_STABLE }}/HISTORY.html"
           target="_blank"
           rel="noopener noreferrer"
           class="badge badge-primary font-weight-normal">
          Kadi4Mat v{{ version }}
        </a>
      </div>
    {% endif %}
  </div>

  {{ template_hook("kadi_get_about_templates") }}
{% endblock %}

kadi/modules/main/templates/main/help.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block breadcrumbs %}
  {% include "snippets/breadcrumb_home.html" %}
  {% snippet "snippets/breadcrumb.html", url=url_for("main.help"), title=title %}
{% endblock %}

{% block content %}
  <div class="card">
    <div class="row">
      <div class="d-none d-lg-block col-lg-3">
        <nav id="help-navbar"
             class="navbar flex-column align-items-stretch overflow-auto vh-75 bg-light border-right">
          <nav class="nav nav-pills flex-column">
            <a href="#login" class="nav-link my-1">
              <strong>{% trans %}Login{% endtrans %}</strong>
            </a>
            <a href="#navigation" class="nav-link my-1">
              <strong>{% trans %}Navigation{% endtrans %}</strong>
            </a>
            <a href="#records" class="nav-link my-1">
              <strong>{% trans %}Records{% endtrans %}</strong>
            </a>
            <a href="#collections" class="nav-link my-1">
              <strong>{% trans %}Collections{% endtrans %}</strong>
            </a>
            <a href="#templates" class="nav-link my-1">
              <strong>{% trans %}Templates{% endtrans %}</strong>
            </a>
            <a href="#users" class="nav-link my-1">
              <strong>{% trans %}Users{% endtrans %}</strong>
            </a>
            <a href="#groups" class="nav-link my-1">
              <strong>{% trans %}Groups{% endtrans %}</strong>
            </a>
            <a href="#settings" class="nav-link my-1">
              <strong>{% trans %}Settings{% endtrans %}</strong>
            </a>
          </nav>
        </nav>
      </div>
      <div class="col-12 col-lg-9">
        <div data-spy="scroll" data-target="#help-navbar" data-offset="200" class="overflow-auto vh-75">
          <div class="mx-3 mt-3 ml-lg-0">
            {% include "main/snippets/help/login.html" %}
            <hr>
            {% include "main/snippets/help/navigation.html" %}
            <hr>
            {% include "main/snippets/help/records.html" %}
            <hr>
            {% include "main/snippets/help/collections.html" %}
            <hr>
            {% include "main/snippets/help/templates.html" %}
            <hr>
            {% include "main/snippets/help/users.html" %}
            <hr>
            {% include "main/snippets/help/groups.html" %}
            <hr>
            {% include "main/snippets/help/settings.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/home.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  <hungry-serpent></hungry-serpent>
  <language-prompt class="mb-4"
                   preferred-locale="{{ preferred_locale }}"
                   cookie-name="{{ const.LOCALE_COOKIE_NAME }}"
                   :cookie-secure="{{ config['LOCALE_COOKIE_SECURE'] | tojson_escaped }}">
  </language-prompt>
  <div class="card text-white border-0 mb-4 banner-gradient">
    <div class="row align-items-center">
      <div class="col-lg-5 d-none d-lg-block">
        <img class="img-fluid rounded" width="425" src="{{ static_url('images/kadi_bg.png') }}">
      </div>
      <div class="col-lg-7 text-center py-3 py-lg-0 mx-3 mx-lg-0">
        <h5>
          <strong>{% trans %}Welcome to Kadi4Mat.{% endtrans %}</strong>
        </h5>
        {% trans %}You are currently logged in as{% endtrans %}
        <identity-popover :user="{{ json_user(current_user) }}">
          <template #default="props">
            <strong class="text-white">{$ kadi.utils.truncate(props.user.displayname, 25) $}</strong>
          </template>
        </identity-popover>.
      </div>
    </div>
  </div>

  {% if not current_user.get_config(const.USER_CONFIG_HIDE_INTRODUCTION) %}
    <div class="d-flex justify-content-between">
      <h4 class="mb-3">
        <strong>{% trans %}Get started{% endtrans %}</strong>
      </h4>
      <a href="{{ url_for('settings.manage_preferences') }}">
        <strong>{% trans %}Hide{% endtrans %}</strong>
      </a>
    </div>
    <div class="card mb-4 bg-light">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-lg-5 mb-2 mb-lg-0">
            <div class="form-row mb-2">
              <div :class="{'col-xl-6': tourActive, 'col-xl-12': !tourActive}">
                <button v-if="!tourActive" type="button" class="btn btn-sm btn-block btn-primary" @click="startTour">
                  <i class="fa-solid fa-lightbulb"></i> {% trans %}Start interactive tour{% endtrans %}
                </button>
                <button v-else type="button" class="btn btn-sm btn-block btn-primary" @click="continueTour">
                  <i class="fa-solid fa-play"></i> {% trans %}Continue tour{% endtrans %}
                </button>
              </div>
              <div v-if="tourActive" class="col-xl-6">
                <button type="button" class="btn btn-sm btn-block btn-white mt-2 mt-xl-0" @click="startTour">
                  <i class="fa-solid fa-rotate"></i> {% trans %}Restart tour{% endtrans %}
                </button>
              </div>
            </div>
            <a href="{{ url_for('main.help') }}" class="btn btn-sm btn-white btn-block">
              <i class="fa-regular fa-circle-question"></i> {% trans %}Check out the help page{% endtrans %}
            </a>
          </div>
          <div class="col-lg-7">
            {% trans %}
              The interactive tour will introduce the most important features of Kadi4Mat and is recommended in order
              to get started. More details and additional information can be found on the help page at any time.
            {% endtrans %}
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <div v-if="kadi.context.favorite_resources.length > 0"
       :class="{'mb-4': kadi.context.saved_searches.length > 0 || kadi.context.latest_resources.length > 0}">
    <div class="d-flex justify-content-between">
      <h4 class="mb-3">
        <strong>{% trans %}Favorites{% endtrans %}</strong>
      </h4>
      <a href="{{ url_for('accounts.view_resources', id=current_user.id) }}">
        <strong>{% trans %}View all{% endtrans %}</strong>
      </a>
    </div>
    <resource-index-view :resources="kadi.context.favorite_resources"></resource-index-view>
  </div>

  <div v-if="kadi.context.saved_searches.length > 0" :class="{'mb-4': kadi.context.latest_resources.length > 0}">
    <div class="d-flex justify-content-between">
      <h4 class="mb-3">
        <strong>{% trans %}Saved searches{% endtrans %}</strong>
      </h4>
    </div>
    <card-deck :items="kadi.context.saved_searches" :max-cards="4">
      <template #default="props">
        <div class="card-header py-1">
          <strong>{$ props.item.pretty_type $}</strong>
        </div>
        <div class="card-body d-flex align-items-center py-2">
          <a class="text-default stretched-link" :href="props.item._links.view">
            <i class="fa-solid fa-magnifying-glass"></i> {$ props.item.name $}
          </a>
        </div>
      </template>
    </card-deck>
  </div>

  <div v-if="kadi.context.latest_resources.length > 0">
    <div class="d-flex justify-content-between">
      <h4 class="mb-3">
        <strong>{% trans %}Latest updates{% endtrans %}</strong>
      </h4>
      <a href="{{ url_for('settings.manage_preferences') }}">
        <strong>{% trans %}Configure{% endtrans %}</strong>
      </a>
    </div>
    <div v-for="(resource, index) in kadi.context.latest_resources">
      <div class="d-flex justify-content-between">
        <h5>
          <strong>{$ resource.title $}</strong>
        </h5>
        <a :href="resource.url">
          <strong>{% trans %}View all{% endtrans %}</strong>
        </a>
      </div>
      <resource-index-view :resources="resource.items"></resource-index-view>
      <br v-if="index < kadi.context.latest_resources.length - 1">
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script nonce="{{ csp_nonce() }}">
    kadi.base.newVue({
      data() {
        return {
          tourActive: false,
        };
      },
      mounted() {
        this.tourActive = kadi.base.tour.hasProgress('basic');
      },
      methods: {
        startTour() {
          kadi.base.tour.start('basic');
          this.tourActive = true;
        },
        continueTour() {
          kadi.base.tour.continue();
        },
      },
    });
  </script>
{% endblock %}

kadi/modules/main/templates/main/index.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  <language-prompt class="mb-4"
                   preferred-locale="{{ preferred_locale }}"
                   cookie-name="{{ const.LOCALE_COOKIE_NAME }}"
                   :cookie-secure="{{ config['LOCALE_COOKIE_SECURE'] | tojson_escaped }}">
  </language-prompt>
  <div class="card text-white border-0 banner-gradient responsive mb-4">
    <div class="row align-items-center">
      <div class="col-lg-5">
        <img class="img-fluid rounded" width="375" src="{{ static_url('images/kadi_bg.png') }}">
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col-lg-6 mb-3 mb-lg-0">
          <span class="font-index">
            {% trans strong_open="<strong>" | safe, strong_close="</strong>" | safe %}
              Welcome to {{ strong_open }}Kadi4Mat{{ strong_close }}, the generic and open source {{ strong_open
              }}virtual research environment{{ strong_close }}.
            {% endtrans %}
          </span>
        </div>
        <div class="col-lg-6">
          <a href="{{ url_for('main.about') }}" class="btn btn-sm btn-block btn-light">
            {% trans %}About{% endtrans %}
          </a>
          <a href="{{ url_for('main.help') }}" class="btn btn-sm btn-block btn-light">
            <i class="fa-regular fa-circle-question"></i> {% trans %}Help{% endtrans %}
          </a>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-12 col-lg-6">
          <div class="form-row">
            <div class="{% if allow_registration() %}col-md-6 mb-2 mb-md-0{% else %}col-md-12{% endif %}">
              <a href="{{ url_for('accounts.login') }}" class="btn btn-block btn-primary">
                {% trans %}Login{% endtrans %}
              </a>
            </div>
            {% if allow_registration() %}
              <div class="col-md-6">
                <a href="{{ url_for('accounts.local_provider_register') }}" class="btn btn-block btn-light">
                  {% trans %}Register{% endtrans %}
                </a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  {% set index_image = get_sys_config(const.SYS_CONFIG_INDEX_IMAGE) %}
  {% set index_text = get_sys_config(const.SYS_CONFIG_INDEX_TEXT) %}

  {% if index_image or index_text %}
    <div class="card bg-light mt-4">
      {% if index_image and index_text %}
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col-lg-auto d-flex justify-content-center d-lg-block max-w-lg-50 mb-3 mb-lg-0">
              <img class="img-thumbnail" src="{{ url_for('api.preview_index_image') }}">
            </div>
            <div class="col-lg">
              <markdown-renderer input="{{ index_text }}"></markdown-renderer>
            </div>
          </div>
        </div>
      {% elif index_image %}
        <div class="card-body text-center">
          <img class="img-thumbnail" src="{{ url_for('api.preview_index_image') }}">
        </div>
      {% elif index_text %}
        <div class="card-body">
          <markdown-renderer input="{{ index_text }}"></markdown-renderer>
        </div>
      {% endif %}
    </div>
  {% endif %}

  {{ template_hook("kadi_get_index_templates") }}
{% endblock %}

kadi/modules/main/templates/main/legals.html
{# Copyright 2022 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block breadcrumbs %}
  {% include "snippets/breadcrumb_home.html" %}
  {% snippet "snippets/breadcrumb.html", url=url_for("main.{}".format(endpoint)), title=title %}
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <markdown-renderer input="{{ get_sys_config(config_item) }}"></markdown-renderer>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/oauth_consent.html
{# Copyright 2023 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  <div class="card">
    <div class="card-header">
      <strong>{% trans %}An application is requesting access to your account{% endtrans %}</strong>
    </div>
    <div class="card-body">
      {% trans client='<a href="{}" target="_blank" rel="noopener noreferrer"><strong>{}</strong></a>'
                      .format(client.client_uri, client.client_name) | safe,
               user='<identity-popover :user="{}" :open-in-new-tab="true"></identity-popover>'
                    .format(json_user(client.user) | escape) | safe %}
        The application {{ client }}, which was created by {{ user }}, is requesting access to your Kadi4Mat account.
        Please verify the authenticity of the application before authorizing it to act on your behalf via the HTTP API
        of Kadi4Mat.
      {% endtrans %}
      <div class="my-2">
        {% trans %}The following permissions/scopes are requested by the application:{% endtrans %}
      </div>
      <div class="card bg-light p-2 pl-3">
        {% if client.scope %}
          <ul class="m-0 pl-3">
            {% for scope in client.scope.split() %}
              <li>
                <pre class="ws-pre-wrap mb-0">{{ scope }}</pre>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <em>{% trans %}None{% endtrans %}</em>
        {% endif %}
      </div>
      <hr>
      <submission-form>
        {{ render_csrf() }}

        <submit-field :field="{{ form.submit_auth }}"></submit-field>
        <submit-field class="btn-danger" :field="{{ form.submit_deny }}"></submit-field>
      </submission-form>
    </div>
  </div>
{% endblock %}